Properly detect python header files
boostorg/boost pull request #321
Opened 2019-08-19 15:51 UTC by yoonghm

The original code use `python -c "import sys; print(sys.prefix)"` which did not show actual directory for include file.

The proper way is `python -c "from sysconfig import get_paths as gp; print(gp()['include'])"`

2019-08-25 22:34 UTC, ali5h commented
with this patch i see the change in `project-config.jam` but `g++` calls still use the wrong include path for python include.

2019-12-03 12:02 UTC, jsharpe commented
This patch is incorrect - the real issue looks to be in boost build - if you don't fully specify version, includes and libraries in the python script it ignores the given version and tries to infer it from sys.version which is missing the m part of the version string.

2019-12-03 12:56 UTC, jsharpe commented
See https://github.com/boostorg/build/issues/481

2020-04-29 00:24 UTC, likan999 commented
I don't see how this could solve the problem. The issue is python.jam that sets the path to `$(prefix)/include/python$(version)`.

2022-12-16 16:25 UTC, Flamefire requested changes
The code looks correct as-is: `$PYTHON_ROOT` gets set to the root of the Python install

2023-12-06 02:47 UTC, closed without merging